import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('merge_group verifier runs only protected-base code with read-only GitHub permissions', () => {
  const workflow = readFileSync(new URL('../.github/workflows/self-architecture-gate.yml', import.meta.url), 'utf8');
  assert.match(workflow, /^name: Self Architecture Gate/m);
  assert.match(workflow, /merge_group:\n    types: \[checks_requested\]\n    branches: \[main\]/);
  assert.match(workflow, /architecture-gate:\n    name: \$\{\{ github\.event_name == 'pull_request_target' && 'architecture-gate' \|\| 'architecture-gate \(not applicable\)' \}\}\n    if: github\.event_name == 'pull_request_target' && github\.event\.pull_request\.draft == false/);
  assert.match(workflow, /merge-group-accept:\n    name: \$\{\{ github\.event_name == 'merge_group' && 'architecture-gate \/ accept' \|\| 'merge-group-accept \(not applicable\)' \}\}\n    if: always\(\) && github\.repository == 'flair-agency\/architecture-gatekeeper' && github\.event_name == 'merge_group' && github\.event\.merge_group\.base_ref == 'refs\/heads\/main'/);
  const mergeJob = workflow.split('\n  merge-group-accept:')[1];
  assert.match(workflow, /merge-group-codex-action-integrity:[\s\S]*?Verify the pinned action before exposing review credentials/);
  assert.match(mergeJob, /needs: \[merge-group-codex-action-integrity\]/);
  assert.match(mergeJob, /Require successful pinned Action integrity verification\n        env:\n          INTEGRITY_RESULT: \$\{\{ needs\.merge-group-codex-action-integrity\.result \}\}\n        run: test "\$INTEGRITY_RESULT" = success/);
  assert.match(mergeJob, /permissions:\n      contents: read\n      pull-requests: read\n      actions: read\n      checks: read\n      attestations: read/);
  assert.match(mergeJob, /Set up Node\.js\n        uses: actions\/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f[\s\S]*?node-version: 22/);
  assert.match(mergeJob, /ref: \$\{\{ github\.event\.merge_group\.base_sha \}\}/);
  assert.doesNotMatch(mergeJob, /GATEKEEPER_RUNTIME_SHA|github\.workflow_sha/);
  assert.match(mergeJob, /event_dir="\$RUNNER_TEMP\/owner-amendment-merge-group"/);
  assert.match(mergeJob, /cp "\$GITHUB_EVENT_PATH" "\$event_dir\/event\.json"/);
  assert.match(mergeJob, /OWNER_AMENDMENT_TAG_RULESET_ID: \$\{\{ vars\.OWNER_AMENDMENT_TAG_RULESET_ID \}\}/);
  assert.match(mergeJob, /working-directory: \$\{\{ runner\.temp \}\}/);
  assert.match(mergeJob, /node "\$GITHUB_WORKSPACE\/scripts\/owner-amendment-merge-group-gate\.mjs"/);
  assert.match(mergeJob, /openai-api-key: \$\{\{ secrets\.OPENAI_API_KEY \}\}/);
  assert.match(mergeJob, /steps\.gate\.outputs\.route == 'ordinary'/);
  assert.match(mergeJob, /uses: flair-agency\/codex-action@643fb31fa44e961453125534c4c7182a5a0a6ba0/);
  assert.match(mergeJob, /timeout-seconds: "240"/);
  assert.match(mergeJob, /safety-strategy: drop-sudo/);
  assert.match(mergeJob, /Require exact-tuple deterministic ordinary PASS/);
  assert.doesNotMatch(mergeJob, /CI_SOURCE_READ_TOKEN|contents: write|pull-requests: write|id-token: write/);
  assert.doesNotMatch(mergeJob, /ref: \$\{\{ github\.event\.merge_group\.head_sha \}\}/);
  assert.match(mergeJob, /contents: read[\s\S]*pull-requests: read[\s\S]*actions: read[\s\S]*attestations: read/);
  assert.doesNotMatch(mergeJob, /contents: write|pull-requests: write|id-token: write/);
  assert.doesNotMatch(workflow, /\.github\/workflows\/owner-amendment-merge-group-accept\.yml/);
  const script = readFileSync(new URL('../scripts/owner-amendment-merge-group-gate.mjs', import.meta.url), 'utf8');
  assert.match(script, /git\(\['rev-parse', 'HEAD'\]\)/);
  assert.match(script, /runtimeRevision !== selection\.bBaseSha/);
  assert.match(script, /eligibilityReviewInputs\(/);
  assert.match(script, /prepared-context\.json/);
  assert.match(script, /git\(\['--no-replace-objects', 'diff', '--binary', '--no-ext-diff', '--no-renames'/);
  assert.match(script, /hash\(promptBytes\) !== prepared\.promptSha256 \|\| hash\(schemaBytes\) !== prepared\.schemaSha256 \|\|\s*hash\(diffBytes\) !== prepared\.diffSha256/);
});

test('merge_group success is pre-transition verification and keeps adoption/canonical placement pending', () => {
  const verifier = readFileSync(new URL('../src/owner-amendment-merge-group-acceptance.mjs', import.meta.url), 'utf8');
  const script = readFileSync(new URL('../scripts/owner-amendment-merge-group-gate.mjs', import.meta.url), 'utf8');
  assert.match(verifier, /status: 'VERIFIED_OWNER_AMENDMENT_G0_FOR_TRANSITION'/);
  assert.doesNotMatch(verifier, /status: 'ACCEPTED_OWNER_AMENDMENT_G0'/);
  assert.match(script, /pre-transition eligibility verified; adoption and canonical placement remain pending/);
  assert.doesNotMatch(script, /OWNER_AMENDMENT \/ G0 accepted:/);
});

test('missing-tag merge-group route selects fresh exact-tuple ordinary PASS verification', () => {
  const script = readFileSync(new URL('../scripts/owner-amendment-merge-group-gate.mjs', import.meta.url), 'utf8');
  const attempts = readFileSync(new URL('../src/owner-amendment-semantic-producer-attempts.mjs', import.meta.url), 'utf8');
  assert.match(script, /inspectOwnerAmendmentSemanticProducerAttempts/);
  assert.match(script, /searchParams\.set\('page', String\(page\)\)/);
  assert.match(script, /const readJobs = async \(\{ runId, runAttempt, page, perPage \}\)/);
  assert.match(script, /jobsUrl\.searchParams\.set\('per_page', String\(perPage\)\)/);
  assert.match(script, /jobsUrl\.searchParams\.set\('page', String\(page\)\)/);
  assert.match(script, /return \{ total_count: result\.total_count, jobs: result\.jobs \}/);
  assert.match(attempts, /runAttempt: String\(runAttempt\)/);
  assert.match(script, /hasSuccessfulSignerBeforeQueue/);
  assert.match(script, /successful pre-queue semantic eligibility signer result but no protected amendment tag/);
  assert.match(script, /selectRoute\('ordinary', selection\)/);
  assert.match(script, /fresh ordinary review of the exact current base\/B tuple/);
  const ordinary = readFileSync(new URL('../src/owner-amendment-merge-group-ordinary-review.mjs', import.meta.url), 'utf8');
  assert.match(ordinary, /prepareOwnerAmendmentMergeGroupOrdinaryReview/);
  assert.match(ordinary, /validateOwnerAmendmentMergeGroupOrdinaryDecision/);
  assert.match(ordinary, /decision\.decision !== 'PASS'/);
});
