import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('candidate wake-up is unprivileged and delegates all verification to the guarded protected receiver', () => {
  const workflow = readFileSync(new URL('../.github/workflows/self-architecture-gate.yml', import.meta.url), 'utf8');
  assert.match(workflow, /^name: Self Architecture Gate/m);
  assert.match(workflow, /pull_request_target:/);
  assert.match(workflow, /branches: \[main\]/);
  assert.match(workflow, /merge_group:\n    types: \[checks_requested\]\n    branches: \[main\]/);
  assert.match(workflow, /architecture-gate:/);
  assert.match(workflow, /if: github\.event_name == 'pull_request_target' && github\.event\.pull_request\.draft == false/);
  assert.match(workflow, /uses: \.\/\.github\/workflows\/architecture-gate\.yml/);
  assert.match(workflow, /merge-group-wakeup:\n    name: merge-group-wakeup[\s\S]*?permissions: \{\}[\s\S]*?run: test "\$GITHUB_EVENT_NAME" = merge_group/);
  const wakeup = workflow.split('\n  merge-group-wakeup:')[1];
  assert.doesNotMatch(wakeup, /secrets\.|OPENAI_API_KEY|actions\/checkout|codex-action@|contents: write|pull-requests: write|checks: write/);
  assert.doesNotMatch(workflow, /architecture-gate \/ accept/);
  const receiver = readFileSync(new URL('../.github/workflows/self-architecture-gate-receiver.yml', import.meta.url), 'utf8');
  assert.match(receiver, /workflow_run:\n    workflows: \[Self Architecture Gate\]\n    types: \[completed\]/);
  const integrity = receiver.split('\n  protected-queue-receiver:')[0];
  assert.match(integrity, /  codex-action-integrity:\n[\s\S]*?permissions:\n      contents: read/);
  assert.match(integrity, /repository: flair-agency\/codex-action\n          ref: 643fb31fa44e961453125534c4c7182a5a0a6ba0[\s\S]*?persist-credentials: false/);
  assert.match(integrity, /verify-codex-action\.mjs[\s\S]*?codex-action-v1\.12-runtime-cancellation\.json[\s\S]*?pnpm install --frozen-lockfile[\s\S]*?pnpm run check[\s\S]*?pnpm test[\s\S]*?git status --short -- dist/);
  assert.doesNotMatch(integrity, /secrets\.|OPENAI_API_KEY|OWNER_AMENDMENT_APP_/);
  assert.match(receiver, /protected-queue-receiver:\n    needs: codex-action-integrity\n    if: needs\.codex-action-integrity\.result == 'success'/);
  assert.match(receiver, /if: github\.repository == 'flair-agency\/architecture-gatekeeper' && github\.ref == 'refs\/heads\/main' && github\.event\.workflow_run\.event == 'merge_group' && vars\.OWNER_AMENDMENT_RECEIVER_ENABLED == 'true'/);
  assert.match(receiver, /environment:\n      name: architecture-gate-self-protected/);
  assert.match(receiver, /permissions:\n      actions: read\n      attestations: read\n      contents: read\n      pull-requests: read/);
  assert.match(receiver, /Check out only the protected default-branch revision\n        uses: actions\/checkout@[a-f0-9]{40}[\s\S]*?ref: \$\{\{ github\.sha \}\}[\s\S]*?persist-credentials: false/);
  assert.doesNotMatch(receiver, /github\.event\.workflow_run\.head_sha|download-artifact|actions: write|contents: write|pull-requests: write|checks: write/);
  assert.match(receiver, /owner-amendment-workflow-run-receiver\.mjs" resolve/);
  assert.match(receiver, /owner-amendment-merge-group-gate\.mjs/);
  assert.match(receiver, /uses: flair-agency\/codex-action@643fb31fa44e961453125534c4c7182a5a0a6ba0/);
  assert.match(receiver, /Run the fresh read-only ordinary review\n        id: ordinary-review\n        if: needs\.codex-action-integrity\.result == 'success' && steps\.prepare-ordinary\.outcome == 'success'/);
  assert.match(receiver, /sandbox: read-only[\s\S]*?safety-strategy: drop-sudo[\s\S]*?timeout-seconds: "240"/);
  assert.match(receiver, /owner-amendment-workflow-run-receiver\.mjs" publish/);
  const publishStep = receiver.split('\n      - name: Publish only the independently verified result')[1];
  assert.match(publishStep, /if: always\(\) && steps\.resolve\.outcome == 'success'/);
  assert.match(publishStep, /OWNER_AMENDMENT_APP_PRIVATE_KEY: \$\{\{ secrets\.OWNER_AMENDMENT_APP_PRIVATE_KEY \}\}/);
  const beforePublish = receiver.split('\n      - name: Publish only the independently verified result')[0];
  assert.doesNotMatch(beforePublish, /OWNER_AMENDMENT_APP_(?:PRIVATE_KEY|ID|INSTALLATION_ID)/);
  assert.match(publishStep, /OWNER_AMENDMENT_APP_ID: \$\{\{ vars\.OWNER_AMENDMENT_APP_ID \}\}/);
  assert.match(publishStep, /OWNER_AMENDMENT_APP_INSTALLATION_ID: \$\{\{ vars\.OWNER_AMENDMENT_APP_INSTALLATION_ID \}\}/);
  const script = readFileSync(new URL('../scripts/owner-amendment-merge-group-gate.mjs', import.meta.url), 'utf8');
  assert.match(script, /adaptVerifiedWorkflowRunContext/);
  assert.match(script, /syntheticVerifiedMergeGroupEvent/);
  assert.doesNotMatch(script, /selectOwnerAmendmentMergeGroupBContext/);
  assert.match(script, /git\(\['rev-parse', 'HEAD'\]\)/);
  assert.match(script, /runtimeRevision !== selection\.bBaseSha/);
  assert.match(script, /eligibilityReviewInputs\(/);
  assert.match(script, /prepared-context\.json/);
  assert.match(script, /git\(\['--no-replace-objects', 'diff', '--binary', '--no-ext-diff', '--no-renames'/);
  assert.match(script, /hash\(promptBytes\) !== prepared\.promptSha256 \|\| hash\(schemaBytes\) !== prepared\.schemaSha256 \|\|\s*hash\(diffBytes\) !== prepared\.diffSha256/);
});

test('merge_group success is pre-transition verification and keeps adoption/canonical placement pending', () => {
  const verifier = readFileSync(new URL('../src/owner-amendment-merge-group-acceptance.mjs', import.meta.url), 'utf8');
  const script = readFileSync(new URL('../scripts/owner-amendment-merge-group-gate.mjs', import.meta.url), 'utf8');
  assert.match(verifier, /status: 'VERIFIED_OWNER_AMENDMENT_G0_FOR_TRANSITION'/);
  assert.doesNotMatch(verifier, /status: 'ACCEPTED_OWNER_AMENDMENT_G0'/);
  assert.match(script, /pre-transition eligibility verified; adoption and canonical placement remain pending/);
  assert.doesNotMatch(script, /OWNER_AMENDMENT \/ G0 accepted:/);
});

test('missing-tag merge-group route selects fresh exact-tuple ordinary PASS verification', () => {
  const script = readFileSync(new URL('../scripts/owner-amendment-merge-group-gate.mjs', import.meta.url), 'utf8');
  const attempts = readFileSync(new URL('../src/owner-amendment-semantic-producer-attempts.mjs', import.meta.url), 'utf8');
  assert.match(script, /inspectOwnerAmendmentSemanticProducerAttempts/);
  assert.match(script, /searchParams\.set\('page', String\(page\)\)/);
  assert.match(script, /const readJobs = async \(\{ runId, runAttempt, page, perPage \}\)/);
  assert.match(script, /jobsUrl\.searchParams\.set\('per_page', String\(perPage\)\)/);
  assert.match(script, /jobsUrl\.searchParams\.set\('page', String\(page\)\)/);
  assert.match(script, /return \{ total_count: result\.total_count, jobs: result\.jobs \}/);
  assert.match(attempts, /runAttempt: String\(runAttempt\)/);
  assert.match(script, /hasSuccessfulSignerBeforeQueue/);
  assert.match(script, /successful pre-queue semantic eligibility signer result but no protected amendment tag/);
  assert.match(script, /selectRoute\('ordinary', selection\)/);
  assert.match(script, /fresh ordinary review of the exact current base\/B tuple/);
  const ordinary = readFileSync(new URL('../src/owner-amendment-merge-group-ordinary-review.mjs', import.meta.url), 'utf8');
  assert.match(ordinary, /prepareOwnerAmendmentMergeGroupOrdinaryReview/);
  assert.match(ordinary, /validateOwnerAmendmentMergeGroupOrdinaryDecision/);
  assert.match(ordinary, /decision\.decision !== 'PASS'/);
});
